# Generated by Django 4.1 on 2024-01-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0006_annee_mois_remove_paiement_periode_paiement_annee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="annee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.annee",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="mois",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.mois",
            ),
        ),
    ]
