# Generated by Django 4.2.7 on 2024-01-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0008_alter_structure_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="diplome",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="lettre_motivation",
        ),
        migrations.CreateModel(
            name="Dossiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
    ]
