# Generated by Django 4.2.7 on 2024-01-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0009_remove_employe_cv_remove_employe_diplome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="prime_astreinte",
            field=models.FloatField(default=0),
        ),
    ]
