# Generated by Django 4.1 on 2024-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0011_paiement_effort_paix"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="indemnite_fonction",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="indemnite_logement",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="indemnite_risque",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="indemnite_transport",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="prime_ancien",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="prime_lait",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="prime_nourriture",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="prime_panier",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="prime_quart",
            field=models.FloatField(null=True),
        ),
    ]
