# Generated by Django 4.1 on 2024-03-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0013_type_paiement_paiement_type_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="dernier_diplome",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.diplome",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="option",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="specialite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.specialite",
            ),
        ),
    ]
