# Generated by Django 4.1 on 2024-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0014_alter_employe_categorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="situation_matrimoniale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.situationmatrimoniale",
            ),
        ),
    ]
