# Generated by Django 4.1 on 2024-03-11 09:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0015_alter_employe_situation_matrimoniale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="description_structure",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
