# Generated by Django 4.1 on 2024-03-11 14:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0016_alter_structure_description_structure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("file", models.FileField(blank=True, null=True, upload_to="contrat/")),
            ],
        ),
        migrations.AddField(
            model_name="employe",
            name="nom_mere",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="nom_pere",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="numero_cnib",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="personne_prevenir",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="photo_cnib",
            field=models.ImageField(blank=True, null=True, upload_to="photos_cnib/"),
        ),
        migrations.AddField(
            model_name="employe",
            name="photo_identite",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos_identite/"
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="profession",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="sous_couvert",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="telephone_prevenir",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="contrat_doc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.contratdoc",
            ),
        ),
    ]
