# Generated by Django 4.1 on 2024-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0017_contratdoc_employe_nom_mere_employe_nom_pere_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type_paiement",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
