# Generated by Django 4.1 on 2024-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0023_contrat_augementation_special_pourcentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="augementation_special_pourcentage",
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="augmentation_octobre_2019",
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="sursalaire",
            field=models.FloatField(default=False),
        ),
    ]
