# Generated by Django 4.1 on 2024-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0024_alter_contrat_augementation_special_pourcentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="augementation_special_pourcentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="paiement",
            name="augmentation_octobre_2019",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="paiement",
            name="sursalaire",
            field=models.FloatField(default=0),
        ),
    ]
