# Generated by Django 4.1 on 2024-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0025_paiement_augementation_special_pourcentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointage",
            name="nb_jour_travail_normal",
            field=models.IntegerField(null=True),
        ),
    ]
