# Generated by Django 4.2.7 on 2024-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elementsalaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule_element", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "elementSal",
            },
        ),
    ]
