# Generated by Django 4.1 on 2024-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="parametre_calcul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_taux_horaire", models.FloatField(null=True)),
                ("min_prime_aciennete", models.FloatField(null=True)),
                ("taux_cnss", models.FloatField(null=True)),
                ("taux_prime_aciennete", models.FloatField(null=True)),
                ("taux_augmentation_prime", models.FloatField(null=True)),
                ("p_prime_quart", models.FloatField(null=True)),
                ("p_prime_panier", models.FloatField(null=True)),
                ("controle_cnss_taux_sal_brute", models.FloatField(null=True)),
                ("controle_cnss_taux_sal_base", models.FloatField(null=True)),
                ("controle_plafond_logement", models.FloatField(null=True)),
                ("controle_plafond_transport", models.FloatField(null=True)),
                ("controle_plafond_fonction", models.FloatField(null=True)),
                ("max_controle_plafond_logement", models.FloatField(null=True)),
                ("max_controle_plafond_transport", models.FloatField(null=True)),
                ("max_controle_plafond_fonction", models.FloatField(null=True)),
                ("taux_abatement_iuts_cadre", models.FloatField(null=True)),
                ("taux_abatement_iuts_non_cadre", models.FloatField(null=True)),
            ],
        ),
    ]
