# Generated by Django 4.1 on 2024-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0002_parametre_calcul_taux_cnss_patronale"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametre_calcul",
            name="tpa",
            field=models.FloatField(null=True),
        ),
    ]
