# Generated by Django 4.1 on 2024-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0003_parametre_calcul_tpa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tranche_charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.FloatField(null=True)),
                ("taux", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tranche_revenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.FloatField(null=True)),
                ("max", models.FloatField(null=True)),
                ("taux", models.FloatField(null=True)),
            ],
        ),
    ]
