# Generated by Django 4.1 on 2024-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0005_parametre_calcul_controle_plafond_panier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametre_calcul",
            name="taux_effort_paix",
            field=models.FloatField(null=True),
        ),
    ]
