# Generated by Django 4.1 on 2024-02-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0006_parametre_calcul_taux_effort_paix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constante_calcule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diviseur_ifc", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Parametre_ifc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taux", models.FloatField(default=0)),
            ],
        ),
    ]
