# Generated by Django 4.1 on 2024-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0007_constante_calcule_parametre_ifc"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametre_calcul",
            name="nb_jour_travail_normal",
            field=models.FloatField(null=True),
        ),
    ]
