# Generated by Django 4.1 on 2024-03-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcul", "0009_alter_parametre_calcul_nb_jour_travail_normal"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametre_calcul",
            name="p_prime_quart_sftp",
            field=models.FloatField(null=True),
        ),
    ]
